// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eflqniojksdfnvasdffb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVmbHFuaW9qa3NkZm52YXNkZmZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2MzYxODUsImV4cCI6MjA2OTIxMjE4NX0.PJG88kdIFYb74FXeZqsb6Jvc_c8UqMa7Gni29xEVWCc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});